### ISSUE TITLE
Missing doors/Fence blocking off hallway in Legion Camp

### ISSUE THREAD

**Issue by mazzinsanity** [f13nametbd/f13tbd#38]
![image](https://github.com/f13nametbd/f13tbd/assets/77054674/df724450-cfb9-4559-be3a-208c3c8556c7)
![image](https://github.com/f13nametbd/f13tbd/assets/77054674/60a1b298-724a-4f56-a691-d364aaab8a31)
![image](https://github.com/f13nametbd/f13tbd/assets/77054674/abe4fa55-bc1b-471e-b25f-5a86d3db83be)

pls fix

**Comment by ZephyrTFA** [comment]
that first one looks intentional as the fence next to it used the broken sprite

**Comment by mazzinsanity** [comment]
> that first one looks intentional as the fence next to it used the broken sprite

If it's for the purpose of letting the Slave role access more of the camp, then regular fence doors that don't have access restrictions on them would work. The fence that blocks the hallway should have a Legion gate in it, so jobs with access are still able to pass.
