### ISSUE TITLE
Flammen is still listed as host in config/admins.txt file

### ISSUE THREAD

**Issue by mazzinsanity** [f13nametbd/f13tbd#6]
---- Screenshots: ----

![image](https://github.com/f13nametbd/f13tbd/assets/77054674/0e2dcf05-0516-4fee-bbeb-ec81e15d2ba2)

Found this while testing. Not sure if it's like this in the real file.

**Comment by mazzinsanity** [comment]
Yeah, the config file is still like this. PLS FIX
https://github.com/f13nametbd/f13tbd/blob/main/config/admins.txt

**Comment by ZephyrTFA** [comment]
config on repo and config on server are not the same; although this could still stand to be removed repo side
